version: '2'

services:
  process:
    image: alfresco/process-services:1.6.0
    environment:
      ACTIVITI_CSRF_DISABLED: 'true'
      ACTIVITI_CORS_ENABLED: 'true'
    #volumes:
    # - "~/.activiti/enterprise-license:/root/.activiti/enterprise-license/:ro"
    ports:
    - 9999:8080
