apiVersion: v1
kind: Pod
metadata:
  name: ps-only
  labels:
    app: web
spec:
  containers:
    - name: process-services
      env:
        - name: ACTIVITI_CORS_ENABLED
          value: 'true'
        - name: ACTIVITI_CSRF_DISABLED
          value: 'true'
      image: alfresco/process-services:latest
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: dockerhub
  restartPolicy: Always
